spring.application.name=cuentasservice
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8888}

server.port=8081

# Config Server
spring.cloud.config.username=admin
spring.cloud.config.password=config2026

# Token interno
service-token.secret=clave-compartida-bff-semana4-2026-1234567890

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# OAuth2 / JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json