mensaje.configuracion=PRUEBA 2 CONFIG CENTRALIZADA

server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Auth Server - JWT
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/.well-known/jwks.json

# Resilience4j
resilience4j.circuitbreaker.instances.estadoExterno.sliding-window-size=5
resilience4j.circuitbreaker.instances.estadoExterno.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.estadoExterno.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.estadoExterno.wait-duration-in-open-state=10s


# Resilience4j - Retry
resilience4j.retry.instances.estadoExterno.max-attempts=3
resilience4j.retry.instances.estadoExterno.wait-duration=1s
resilience4j.retry.instances.estadoExterno.enable-exponential-backoff=true
resilience4j.retry.instances.estadoExterno.exponential-backoff-multiplier=2