name: Deploy Semana 7

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: "semana 7/package-lock.json"

      - name: Instalar dependencias
        working-directory: "semana 7"
        run: npm ci

      - name: Construir proyecto
        working-directory: "semana 7"
        run: npm run build

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Subir sitio
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./semana 7/dist"

      - name: Publicar
        id: deployment
        uses: actions/deploy-pages@v4
